
;**************************************************************************
;
;		SIX FANTASIES MACHINE, version 0.50beta
;
;**************************************************************************
;A sound making tool based on Six Fantasies on a Poem by Thomas 
;Campion by Paul Lansky. The tool uses LPC analysis/resynthesis 
;and filtering to emulate the range of vocal transformations that 
;can be heard in Lansky's piece.

;Copyright (C) 2009  Andreas Bergsland
;
;This program is free software: you can redistribute it and/or modify
;it under the terms of the GNU General Public License as published by
;the Free Software Foundation, either version 3 of the License, or
;(at your option) any later version.
;
;This program is distributed in the hope that it will be useful,
;but WITHOUT ANY WARRANTY; without even the implied warranty of
;MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;GNU General Public License for more details.
;
;You should have received a copy of the GNU General Public License
;along with this program.  If not, see <http://www.gnu.org/licenses/>.

;***************************************************************************

;Copy_paste_instruments.inc


;++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
;		COPY / PASTE instruments
;++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

	instr	201
$COPYFTP(1)
	endin

	instr 	202
$COPYFTP(2)
	endin

	instr 	203
$COPYFTP(3)
	endin

	instr	204
$COPYFTP(4)
	endin

	instr	205
$COPYFTP(5)
	endin

	instr	206
$COPYFTP(6)
	endin

	instr	207
$COPYFTP(7)
	endin

	instr	208
$COPYFTP(8)
	endin

	instr	211
$COPYSFS(1)
	endin

	instr	212
$COPYSFS(2)
	endin

	instr	213
$COPYSFS(3)
	endin

	instr	214
$COPYSFS(4)
	endin

	instr	215
$COPYSFS(5)
	endin

	instr	216
$COPYSFS(6)
	endin

	instr	217
$COPYSFS(7)
	endin

	instr	218
$COPYSFS(8)
	endin

	instr	221
$COPYPchVal(1)
	endin

	instr	222
$COPYPchVal(2)
	endin

	instr	223
$COPYPchVal(3)
	endin

	instr	224
$COPYPchVal(4)
	endin

	instr	225
$COPYPchVal(5)
	endin

	instr	226
$COPYPchVal(6)
	endin

	instr	227
$COPYPchVal(7)
	endin

	instr	228
$COPYPchVal(8)
	endin

	instr	231
$COPYDiv(1)
	endin

	instr	232
$COPYDiv(2)
	endin

	instr	233
$COPYDiv(3)
	endin

	instr	234
$COPYDiv(4)
	endin

	instr	235
$COPYDiv(5)
	endin

	instr	236
$COPYDiv(6)
	endin

	instr	237
$COPYDiv(7)
	endin

	instr	238
$COPYDiv(8)
	endin

	instr	241
$COPYFTP(1)
$COPYSFS(1)
$COPYPchVal(1)
$COPYDiv(1)
	endin

	instr	242
$COPYFTP(2)
$COPYSFS(2)
$COPYPchVal(2)
$COPYDiv(2)
	endin

	instr	243
$COPYFTP(3)
$COPYSFS(3)
$COPYPchVal(3)
$COPYDiv(3)
	endin

	instr	244
$COPYFTP(4)
$COPYSFS(4)
$COPYPchVal(4)
$COPYDiv(4)
	endin

	instr	245
$COPYFTP(5)
$COPYSFS(5)
$COPYPchVal(5)
$COPYDiv(5)
	endin

	instr	246
$COPYFTP(6)
$COPYSFS(6)
$COPYPchVal(6)
$COPYDiv(6)
	endin

	instr	247
$COPYFTP(7)
$COPYSFS(7)
$COPYPchVal(7)
$COPYDiv(7)
	endin

	instr	248
$COPYFTP(8)
$COPYSFS(8)
$COPYPchVal(8)
$COPYDiv(8)
	endin

; PASTE
	instr	301
$PASTEFTP(1)
	endin

	instr 	302
$PASTEFTP(2)
	endin

	instr 	303
$PASTEFTP(3)
	endin

	instr	304
$PASTEFTP(4)
	endin


	instr	305
$PASTEFTP(5)
	endin


	instr	306
$PASTEFTP(6)
	endin


	instr	307
$PASTEFTP(7)
	endin


	instr	308
$PASTEFTP(8)
	endin

	instr	311
$PASTESFS(1)
	endin

	instr	312
$PASTESFS(2)
	endin

	instr	313
$PASTESFS(3)
	endin

	instr	314
$PASTESFS(4)
	endin

	instr	315
$PASTESFS(5)
	endin

	instr	316
$PASTESFS(6)
	endin

	instr	317
$PASTESFS(7)
	endin

	instr	318
$PASTESFS(8)
	endin

	instr	321
$PASTEPchVal(1)
	endin

	instr	322
$PASTEPchVal(2)
	endin

	instr	323
$PASTEPchVal(3)
	endin

	instr	324
$PASTEPchVal(4)
	endin

	instr	325
$PASTEPchVal(4)
	endin

	instr	326
$PASTEPchVal(4)
	endin

	instr	327
$PASTEPchVal(4)
	endin

	instr	328
$PASTEPchVal(4)
	endin

	instr	331
$PASTEDiv(1)
	endin

	instr	332
$PASTEDiv(2)
	endin

	instr	333
$PASTEDiv(3)
	endin

	instr	334
$PASTEDiv(4)
	endin

	instr	335
$PASTEDiv(5)
	endin

	instr	336
$PASTEDiv(6)
	endin

	instr	337
$PASTEDiv(7)
	endin

	instr	338
$PASTEDiv(8)
	endin

	instr	341
$PASTEFTP(1)
$PASTESFS(1)
$PASTEPchVal(1)
$PASTEDiv(1)
	endin

	instr	342
$PASTEFTP(2)
$PASTESFS(2)
$PASTEPchVal(2)
$PASTEDiv(2)
	endin

	instr	343
$PASTEFTP(3)
$PASTESFS(3)
$PASTEPchVal(3)
$PASTEDiv(3)
	endin

	instr	344
$PASTEFTP(4)
$PASTESFS(4)
$PASTEPchVal(4)
$PASTEDiv(4)
	endin

	instr	345
$PASTEFTP(5)
$PASTESFS(5)
$PASTEPchVal(5)
$PASTEDiv(5)
	endin

	instr	346
$PASTEFTP(6)
$PASTESFS(6)
$PASTEPchVal(6)
$PASTEDiv(6)
	endin

	instr	347
$PASTEFTP(7)
$PASTESFS(7)
$PASTEPchVal(7)
$PASTEDiv(7)
	endin

	instr	348
$PASTEFTP(8)
$PASTESFS(8)
$PASTEPchVal(8)
$PASTEDiv(8)
	endin

	instr	351
$DefaultDur(1)
	endin

	instr	352
$DefaultDur(2)
	endin

	instr	353
$DefaultDur(3)
	endin

	instr	354
$DefaultDur(4)
	endin

	instr	355
$DefaultDur(5)
	endin

	instr	356
$DefaultDur(6)
	endin

	instr	357
$DefaultDur(7)
	endin

	instr	358
$DefaultDur(8)
	endin