
;**************************************************************************
;
;		SIX FANTASIES MACHINE, version 0.50beta
;
;**************************************************************************
;A sound making tool based on Six Fantasies on a Poem by Thomas 
;Campion by Paul Lansky. The tool uses LPC analysis/resynthesis 
;and filtering to emulate the range of vocal transformations that 
;can be heard in Lansky's piece.

;Copyright (C) 2009  Andreas Bergsland
;
;This program is free software: you can redistribute it and/or modify
;it under the terms of the GNU General Public License as published by
;the Free Software Foundation, either version 3 of the License, or
;(at your option) any later version.
;
;This program is distributed in the hope that it will be useful,
;but WITHOUT ANY WARRANTY; without even the implied warranty of
;MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;GNU General Public License for more details.
;
;You should have received a copy of the GNU General Public License
;along with this program.  If not, see <http://www.gnu.org/licenses/>.

;***************************************************************************

; Set_strings_WriteFile.inc

strset		50000, "snd/SixFantasiesSound"

strset		50001, "1"
strset		50002, "2"
strset		50003, "3"
strset		50004, "4"
strset		50005, "5"
strset		50006, "6"
strset		50007, "7"
strset		50008, "8"
strset		50009, "9"
strset		50010, "10"
strset		50011, "11"
strset		50012, "12"
strset		50013, "13"
strset		50014, "14"
strset		50015, "15"
strset		50016, "16"
strset		50017, "17"
strset		50018, "18"
strset		50019, "19"
strset		50020, "20"
strset		50021, "21"
strset		50022, "22"
strset		50023, "23"
strset		50024, "24"
strset		50025, "25"
strset		50026, "26"
strset		50027, "27"
strset		50028, "28"
strset		50029, "29"
strset		50030, "30"
strset		50031, "31"
strset		50032, "32"
strset		50033, "33"
strset		50034, "34"
strset		50035, "35"
strset		50036, "36"
strset		50037, "37"
strset		50038, "38"
strset		50039, "39"
strset		50040, "40"
strset		50041, "41"
strset		50042, "42"
strset		50043, "43"
strset		50044, "44"
strset		50045, "45"
strset		50046, "46"
strset		50047, "47"
strset		50048, "48"
strset		50049, "49"
strset		50050, "50"


