
;**************************************************************************
;
;		SIX FANTASIES MACHINE, version 0.50beta
;
;**************************************************************************
;A sound making tool based on Six Fantasies on a Poem by Thomas 
;Campion by Paul Lansky. The tool uses LPC analysis/resynthesis 
;and filtering to emulate the range of vocal transformations that 
;can be heard in Lansky's piece.

;Copyright (C) 2009  Andreas Bergsland
;
;This program is free software: you can redistribute it and/or modify
;it under the terms of the GNU General Public License as published by
;the Free Software Foundation, either version 3 of the License, or
;(at your option) any later version.
;
;This program is distributed in the hope that it will be useful,
;but WITHOUT ANY WARRANTY; without even the implied warranty of
;MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;GNU General Public License for more details.
;
;You should have received a copy of the GNU General Public License
;along with this program.  If not, see <http://www.gnu.org/licenses/>.

;***************************************************************************

; Set_strings_phrases.inc

strset		10001, "Rose cheeked Lawra"
strset		10002, "Come"
strset		10003, "Sing thou smoothly with thy bewties"
strset		10004, "Silent Musick"
strset		10005, "Either Other"
strset		10006, "Sweetly Gracing"
strset		10007, "Lovely formes do flowe"
strset		10008, "From Consent Divenely Framed"
strset		10009, "Heaven is Musick"
strset		10010, "And Thy Beawties Birth"
strset		10011, "Is heavenly"
strset		10012, "These dull notes we sing"
strset		10013, "Discords Needs for Helps to Grace Them"
strset		10014, "Only Beawty Purely Loving"
strset		10015, "Knows no discord"
strset		10016, "But still"
strset		10017, "Moves Delight"
strset		10018, "Like Clear Springs Renued by Flowing"
strset		10019, "Ever perfect"
strset		10020, "Ever in Themselves"
strset		10021, "Eternall"